void main() {
  // TODO test that errors and exceptions are handled gracefully and don't throw exceptions further up the chain
}